
services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: resalab-database
    environment:
      POSTGRES_DB: resalab_db
      POSTGRES_USER: resalab_user
      POSTGRES_PASSWORD: password
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s

  pgadmin:
    image: dpage/pgadmin4
    container_name: resalab-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@resalab.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - database

  mailer:
    image: axllent/mailpit/
    container_name: resalab-mailer
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI

volumes:
  database_data:
